import React from 'react';
import CreatePost from '../CreatePost/CreatePost';

const MainHome = () => {
    return (
        <div className='pt-10 w-[750px]'>

            <CreatePost />


            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
            <h1>this is the main home pages</h1>
        </div>
    );
};

export default MainHome;